# Generated by Django 4.0.2 on 2022-02-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_calculations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
