# Generated by Django 4.0.2 on 2022-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
    ]
