# Generated by Django 4.0.2 on 2022-02-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_calculations'),
        ('calculator', '0005_alter_calculations_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
