# Generated by Django 4.0.2 on 2022-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_calculations_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
