# Generated by Django 4.0.2 on 2022-02-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_remove_calculations_entries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculations',
        ),
    ]
